### ISSUE TITLE
Bug: when creating a minimum project, input config is required

### ISSUE THREAD

**Issue by gocs** [x-hgg-x/goecsengine#1]
https://github.com/x-hgg-x/goecsengine/blob/1c0712164a4656d0691fe7e1e1bd0744a2e6a6e5/systems/input/input.go#L15

Error:
> panic: runtime error: invalid memory address or nil pointer dereference

I think the `world.Resources.Controls.Axes` is nil, because I intentionally don't create any toml configs

Would it be better if we would not require users to create a input config?🤔 maybe just a set of sprites, text entities, and actions? if not maybe I'll create a pull request to add a guard to remind users to create a `controls.toml` config
What would be the required entities to create a minimum project?

**Comment by x-hgg-x** [comment]
I have fixed the bug and added a minimum example in https://github.com/x-hgg-x/goecsengine/commit/ae5034bc1f8d1fec28494fa6435b1e4996b4aee6.

Updated in https://github.com/x-hgg-x/goecsengine/commit/9c7cd1d842e15cd29cd09d39b45ef9047079726e.
